sudo: false

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle compile test:compile test
  - sbt ++$TRAVIS_SCALA_VERSION docs/tut
  - sbt ++$TRAVIS_SCALA_VERSION docs_cats/tut

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database world;' -U postgres
  - psql -c '\i world.sql' -d world -U postgres
  - psql -d world -c "create extension postgis" -U postgres
  - psql -d world -c "create type myenum as enum ('foo', 'bar')" -U postgres

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0d4c1d733e9259a3db54
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
