# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: mdillon/postgis:11 # postgres with postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: world
    ports:
      - 5432:5432
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/

  mysql:
    image: mysql:5.7-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: world
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8686:8080

